spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test;MODE=MySQL;INIT=CREATE SCHEMA IF NOT EXISTS "public"
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: com.itexchange.demo.mybank.CustomH2Dialect